name: Release Action
run-name: ${{ github.actor }} has created a new release 🚀

on: [push]

jobs:
    release:
        runs-on: ubuntu-20.04
        steps:
            - name: Check out the repository to the runner
              uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install the dependencies
              run: yarn
            - name: Create a release
              run: yarn release
